/**
 * Seed universe of heavily-traded US-listed equities & ETFs.
 * Order doubles as a popularity boost for search ranking.
 * Runtime search extends this list infinitely via live lookup.
 *
 * Tuple: [symbol, name, exchange, sector]
 */
export const STOCK_UNIVERSE: ReadonlyArray<readonly [string, string, string, string]> = [
  /* ---- Mega-cap tech ---- */
  ["AAPL", "Apple Inc.", "NASDAQ", "Technology"],
  ["MSFT", "Microsoft Corporation", "NASDAQ", "Technology"],
  ["NVDA", "NVIDIA Corporation", "NASDAQ", "Technology"],
  ["GOOGL", "Alphabet Inc. Class A", "NASDAQ", "Communication Services"],
  ["GOOG", "Alphabet Inc. Class C", "NASDAQ", "Communication Services"],
  ["AMZN", "Amazon.com Inc.", "NASDAQ", "Consumer Discretionary"],
  ["META", "Meta Platforms Inc.", "NASDAQ", "Communication Services"],
  ["AVGO", "Broadcom Inc.", "NASDAQ", "Technology"],
  ["TSLA", "Tesla Inc.", "NASDAQ", "Consumer Discretionary"],
  ["NFLX", "Netflix Inc.", "NASDAQ", "Communication Services"],
  ["ORCL", "Oracle Corporation", "NYSE", "Technology"],
  ["ADBE", "Adobe Inc.", "NASDAQ", "Technology"],
  ["CRM", "Salesforce Inc.", "NYSE", "Technology"],
  ["AMD", "Advanced Micro Devices Inc.", "NASDAQ", "Technology"],
  ["INTC", "Intel Corporation", "NASDAQ", "Technology"],
  ["QCOM", "QUALCOMM Inc.", "NASDAQ", "Technology"],
  ["TXN", "Texas Instruments Inc.", "NASDAQ", "Technology"],
  ["MU", "Micron Technology Inc.", "NASDAQ", "Technology"],
  ["AMAT", "Applied Materials Inc.", "NASDAQ", "Technology"],
  ["LRCX", "Lam Research Corporation", "NASDAQ", "Technology"],
  ["KLAC", "KLA Corporation", "NASDAQ", "Technology"],
  ["ASML", "ASML Holding NV", "NASDAQ", "Technology"],
  ["TSM", "Taiwan Semiconductor Manufacturing Co.", "NYSE", "Technology"],
  ["IBM", "International Business Machines Corp.", "NYSE", "Technology"],
  ["CSCO", "Cisco Systems Inc.", "NASDAQ", "Technology"],
  ["ACN", "Accenture plc", "NYSE", "Technology"],
  ["NOW", "ServiceNow Inc.", "NYSE", "Technology"],
  ["INTU", "Intuit Inc.", "NASDAQ", "Technology"],
  ["PANW", "Palo Alto Networks Inc.", "NASDAQ", "Technology"],
  ["ANET", "Arista Networks Inc.", "NYSE", "Technology"],
  ["SNPS", "Synopsys Inc.", "NASDAQ", "Technology"],
  ["CDNS", "Cadence Design Systems Inc.", "NASDAQ", "Technology"],
  ["PLTR", "Palantir Technologies Inc.", "NASDAQ", "Technology"],
  ["SHOP", "Shopify Inc.", "NYSE", "Technology"],
  ["UBER", "Uber Technologies Inc.", "NYSE", "Industrials"],
  ["ABNB", "Airbnb Inc.", "NASDAQ", "Consumer Discretionary"],
  ["BKNG", "Booking Holdings Inc.", "NASDAQ", "Consumer Discretionary"],
  ["MRVL", "Marvell Technology Inc.", "NASDAQ", "Technology"],
  ["NXPI", "NXP Semiconductors NV", "NASDAQ", "Technology"],
  ["ON", "ON Semiconductor Corporation", "NASDAQ", "Technology"],
  ["MPWR", "Monolithic Power Systems Inc.", "NASDAQ", "Technology"],
  ["SWKS", "Skyworks Solutions Inc.", "NASDAQ", "Technology"],
  ["QRVO", "Qorvo Inc.", "NASDAQ", "Technology"],
  ["ARM", "Arm Holdings plc", "NASDAQ", "Technology"],
  ["SMCI", "Super Micro Computer Inc.", "NASDAQ", "Technology"],
  ["DELL", "Dell Technologies Inc.", "NYSE", "Technology"],
  ["HPE", "Hewlett Packard Enterprise Co.", "NYSE", "Technology"],
  ["HPQ", "HP Inc.", "NYSE", "Technology"],
  ["DDOG", "Datadog Inc.", "NASDAQ", "Technology"],
  ["NET", "Cloudflare Inc.", "NYSE", "Technology"],
  ["CRWD", "CrowdStrike Holdings Inc.", "NASDAQ", "Technology"],
  ["ZS", "Zscaler Inc.", "NASDAQ", "Technology"],
  ["OKTA", "Okta Inc.", "NASDAQ", "Technology"],
  ["SNOW", "Snowflake Inc.", "NYSE", "Technology"],
  ["MDB", "MongoDB Inc.", "NASDAQ", "Technology"],
  ["TEAM", "Atlassian Corporation", "NASDAQ", "Technology"],
  ["HUBS", "HubSpot Inc.", "NYSE", "Technology"],
  ["WDAY", "Workday Inc.", "NASDAQ", "Technology"],
  ["TWLO", "Twilio Inc.", "NYSE", "Technology"],
  ["AI", "C3.ai Inc.", "NYSE", "Technology"],
  ["PATH", "UiPath Inc.", "NYSE", "Technology"],
  ["U", "Unity Software Inc.", "NYSE", "Technology"],
  ["ROP", "Roper Technologies Inc.", "NASDAQ", "Technology"],
  ["FTNT", "Fortinet Inc.", "NASDAQ", "Technology"],
  ["ADSK", "Autodesk Inc.", "NASDAQ", "Technology"],
  ["TEAM", "Atlassian Corporation", "NASDAQ", "Technology"],
  ["VRSN", "VeriSign Inc.", "NASDAQ", "Technology"],
  ["PAYX", "Paychex Inc.", "NASDAQ", "Industrials"],
  ["FICO", "Fair Isaac Corporation", "NYSE", "Technology"],

  /* ---- Communication & media ---- */
  ["DIS", "The Walt Disney Company", "NYSE", "Communication Services"],
  ["CMCSA", "Comcast Corporation", "NASDAQ", "Communication Services"],
  ["T", "AT&T Inc.", "NYSE", "Communication Services"],
  ["VZ", "Verizon Communications Inc.", "NYSE", "Communication Services"],
  ["TMUS", "T-Mobile US Inc.", "NASDAQ", "Communication Services"],
  ["CHTR", "Charter Communications Inc.", "NASDAQ", "Communication Services"],
  ["EA", "Electronic Arts Inc.", "NASDAQ", "Communication Services"],
  ["TTWO", "Take-Two Interactive Software Inc.", "NASDAQ", "Communication Services"],
  ["RBLX", "Roblox Corporation", "NYSE", "Communication Services"],
  ["SPOT", "Spotify Technology S.A.", "NYSE", "Communication Services"],
  ["WBD", "Warner Bros. Discovery Inc.", "NASDAQ", "Communication Services"],
  ["PINS", "Pinterest Inc.", "NYSE", "Communication Services"],
  ["SNAP", "Snap Inc.", "NYSE", "Communication Services"],
  ["MTCH", "Match Group Inc.", "NASDAQ", "Communication Services"],
  ["LYV", "Live Nation Entertainment Inc.", "NYSE", "Communication Services"],

  /* ---- Financials ---- */
  ["BRK-B", "Berkshire Hathaway Inc. Class B", "NYSE", "Financials"],
  ["JPM", "JPMorgan Chase & Co.", "NYSE", "Financials"],
  ["V", "Visa Inc.", "NYSE", "Financials"],
  ["MA", "Mastercard Incorporated", "NYSE", "Financials"],
  ["BAC", "Bank of America Corporation", "NYSE", "Financials"],
  ["WFC", "Wells Fargo & Company", "NYSE", "Financials"],
  ["GS", "The Goldman Sachs Group Inc.", "NYSE", "Financials"],
  ["MS", "Morgan Stanley", "NYSE", "Financials"],
  ["C", "Citigroup Inc.", "NYSE", "Financials"],
  ["AXP", "American Express Company", "NYSE", "Financials"],
  ["BX", "Blackstone Inc.", "NYSE", "Financials"],
  ["BLK", "BlackRock Inc.", "NYSE", "Financials"],
  ["SCHW", "The Charles Schwab Corporation", "NYSE", "Financials"],
  ["COF", "Capital One Financial Corporation", "NYSE", "Financials"],
  ["USB", "U.S. Bancorp", "NYSE", "Financials"],
  ["PNC", "The PNC Financial Services Group Inc.", "NYSE", "Financials"],
  ["TFC", "Truist Financial Corporation", "NYSE", "Financials"],
  ["BK", "The Bank of New York Mellon Corp.", "NYSE", "Financials"],
  ["ICE", "Intercontinental Exchange Inc.", "NYSE", "Financials"],
  ["CME", "CME Group Inc.", "NASDAQ", "Financials"],
  ["SPGI", "S&P Global Inc.", "NYSE", "Financials"],
  ["MCO", "Moody's Corporation", "NYSE", "Financials"],
  ["PYPL", "PayPal Holdings Inc.", "NASDAQ", "Financials"],
  ["XYZ", "Block Inc.", "NYSE", "Financials"],
  ["FIS", "Fidelity National Information Services", "NYSE", "Financials"],
  ["FI", "Fiserv Inc.", "NYSE", "Financials"],
  ["COIN", "Coinbase Global Inc.", "NASDAQ", "Financials"],
  ["HOOD", "Robinhood Markets Inc.", "NASDAQ", "Financials"],
  ["SOFI", "SoFi Technologies Inc.", "NASDAQ", "Financials"],
  ["AFRM", "Affirm Holdings Inc.", "NASDAQ", "Financials"],
  ["NU", "Nu Holdings Ltd.", "NYSE", "Financials"],
  ["CB", "Chubb Limited", "NYSE", "Financials"],
  ["MMC", "Marsh & McLennan Companies Inc.", "NYSE", "Financials"],
  ["AON", "Aon plc", "NYSE", "Financials"],
  ["MET", "MetLife Inc.", "NYSE", "Financials"],
  ["PRU", "Prudential Financial Inc.", "NYSE", "Financials"],
  ["AFL", "Aflac Incorporated", "NYSE", "Financials"],
  ["AIG", "American International Group Inc.", "NYSE", "Financials"],
  ["TRV", "The Travelers Companies Inc.", "NYSE", "Financials"],
  ["ALL", "The Allstate Corporation", "NYSE", "Financials"],
  ["PGR", "The Progressive Corporation", "NYSE", "Financials"],
  ["KKR", "KKR & Co. Inc.", "NYSE", "Financials"],
  ["APO", "Apollo Global Management Inc.", "NYSE", "Financials"],
  ["ARES", "Ares Management Corporation", "NYSE", "Financials"],
  ["NDAQ", "Nasdaq Inc.", "NASDAQ", "Financials"],

  /* ---- Health care ---- */
  ["UNH", "UnitedHealth Group Incorporated", "NYSE", "Health Care"],
  ["LLY", "Eli Lilly and Company", "NYSE", "Health Care"],
  ["JNJ", "Johnson & Johnson", "NYSE", "Health Care"],
  ["ABBV", "AbbVie Inc.", "NYSE", "Health Care"],
  ["MRK", "Merck & Co. Inc.", "NYSE", "Health Care"],
  ["PFE", "Pfizer Inc.", "NYSE", "Health Care"],
  ["TMO", "Thermo Fisher Scientific Inc.", "NYSE", "Health Care"],
  ["ABT", "Abbott Laboratories", "NYSE", "Health Care"],
  ["DHR", "Danaher Corporation", "NYSE", "Health Care"],
  ["AMGN", "Amgen Inc.", "NASDAQ", "Health Care"],
  ["BMY", "Bristol-Myers Squibb Company", "NYSE", "Health Care"],
  ["GILD", "Gilead Sciences Inc.", "NASDAQ", "Health Care"],
  ["VRTX", "Vertex Pharmaceuticals Inc.", "NASDAQ", "Health Care"],
  ["REGN", "Regeneron Pharmaceuticals Inc.", "NASDAQ", "Health Care"],
  ["ISRG", "Intuitive Surgical Inc.", "NASDAQ", "Health Care"],
  ["MDT", "Medtronic plc", "NYSE", "Health Care"],
  ["SYK", "Stryker Corporation", "NYSE", "Health Care"],
  ["BDX", "Becton Dickinson and Company", "NYSE", "Health Care"],
  ["ZTS", "Zoetis Inc.", "NYSE", "Health Care"],
  ["CVS", "CVS Health Corporation", "NYSE", "Health Care"],
  ["MCK", "McKesson Corporation", "NYSE", "Health Care"],
  ["CI", "The Cigna Group", "NYSE", "Health Care"],
  ["ELV", "Elevance Health Inc.", "NYSE", "Health Care"],
  ["HUM", "Humana Inc.", "NYSE", "Health Care"],
  ["BSX", "Boston Scientific Corporation", "NYSE", "Health Care"],
  ["EW", "Edwards Lifesciences Corporation", "NYSE", "Health Care"],
  ["HCA", "HCA Healthcare Inc.", "NYSE", "Health Care"],
  ["IDXX", "IDEXX Laboratories Inc.", "NASDAQ", "Health Care"],
  ["MRNA", "Moderna Inc.", "NASDAQ", "Health Care"],
  ["BIIB", "Biogen Inc.", "NASDAQ", "Health Care"],
  ["DXCM", "DexCom Inc.", "NASDAQ", "Health Care"],
  ["PODD", "Insulet Corporation", "NASDAQ", "Health Care"],
  ["ALNY", "Alnylam Pharmaceuticals Inc.", "NASDAQ", "Health Care"],
  ["NVO", "Novo Nordisk A/S", "NYSE", "Health Care"],
  ["NVS", "Novartis AG", "NYSE", "Health Care"],
  ["AZN", "AstraZeneca PLC", "NASDAQ", "Health Care"],
  ["SNY", "Sanofi", "NASDAQ", "Health Care"],
  ["GEHC", "GE HealthCare Technologies Inc.", "NASDAQ", "Health Care"],
  ["COR", "Cencora Inc.", "NYSE", "Health Care"],
  ["CAH", "Cardinal Health Inc.", "NYSE", "Health Care"],

  /* ---- Consumer ---- */
  ["WMT", "Walmart Inc.", "NYSE", "Consumer Staples"],
  ["COST", "Costco Wholesale Corporation", "NASDAQ", "Consumer Staples"],
  ["PG", "The Procter & Gamble Company", "NYSE", "Consumer Staples"],
  ["KO", "The Coca-Cola Company", "NYSE", "Consumer Staples"],
  ["PEP", "PepsiCo Inc.", "NASDAQ", "Consumer Staples"],
  ["PM", "Philip Morris International Inc.", "NYSE", "Consumer Staples"],
  ["MO", "Altria Group Inc.", "NYSE", "Consumer Staples"],
  ["CL", "Colgate-Palmolive Company", "NYSE", "Consumer Staples"],
  ["KMB", "Kimberly-Clark Corporation", "NASDAQ", "Consumer Staples"],
  ["MDLZ", "Mondelez International Inc.", "NASDAQ", "Consumer Staples"],
  ["GIS", "General Mills Inc.", "NYSE", "Consumer Staples"],
  ["K", "Kellanova", "NYSE", "Consumer Staples"],
  ["HSY", "The Hershey Company", "NYSE", "Consumer Staples"],
  ["MNST", "Monster Beverage Corporation", "NASDAQ", "Consumer Staples"],
  ["KDP", "Keurig Dr Pepper Inc.", "NASDAQ", "Consumer Staples"],
  ["CELH", "Celsius Holdings Inc.", "NASDAQ", "Consumer Staples"],
  ["STZ", "Constellation Brands Inc.", "NYSE", "Consumer Staples"],
  ["TAP", "Molson Coors Beverage Company", "NYSE", "Consumer Staples"],
  ["SJM", "The J.M. Smucker Company", "NYSE", "Consumer Staples"],
  ["TSN", "Tyson Foods Inc.", "NYSE", "Consumer Staples"],
  ["HD", "The Home Depot Inc.", "NYSE", "Consumer Discretionary"],
  ["LOW", "Lowe's Companies Inc.", "NYSE", "Consumer Discretionary"],
  ["MCD", "McDonald's Corporation", "NYSE", "Consumer Discretionary"],
  ["SBUX", "Starbucks Corporation", "NASDAQ", "Consumer Discretionary"],
  ["NKE", "NIKE Inc.", "NYSE", "Consumer Discretionary"],
  ["TGT", "Target Corporation", "NYSE", "Consumer Discretionary"],
  ["TJX", "The TJX Companies Inc.", "NYSE", "Consumer Discretionary"],
  ["DG", "Dollar General Corporation", "NYSE", "Consumer Discretionary"],
  ["DLTR", "Dollar Tree Inc.", "NASDAQ", "Consumer Discretionary"],
  ["YUM", "Yum! Brands Inc.", "NYSE", "Consumer Discretionary"],
  ["CMG", "Chipotle Mexican Grill Inc.", "NYSE", "Consumer Discretionary"],
  ["DPZ", "Domino's Pizza Inc.", "NYSE", "Consumer Discretionary"],
  ["MAR", "Marriott International Inc.", "NASDAQ", "Consumer Discretionary"],
  ["HLT", "Hilton Worldwide Holdings Inc.", "NYSE", "Consumer Discretionary"],
  ["LVS", "Las Vegas Sands Corp.", "NYSE", "Consumer Discretionary"],
  ["WYNN", "Wynn Resorts Limited", "NASDAQ", "Consumer Discretionary"],
  ["MGM", "MGM Resorts International", "NYSE", "Consumer Discretionary"],
  ["RCL", "Royal Caribbean Cruises Ltd.", "NYSE", "Consumer Discretionary"],
  ["CCL", "Carnival Corporation", "NYSE", "Consumer Discretionary"],
  ["LULU", "Lululemon Athletica Inc.", "NASDAQ", "Consumer Discretionary"],
  ["ROST", "Ross Stores Inc.", "NASDAQ", "Consumer Discretionary"],
  ["ORLY", "O'Reilly Automotive Inc.", "NASDAQ", "Consumer Discretionary"],
  ["AZO", "AutoZone Inc.", "NYSE", "Consumer Discretionary"],
  ["EBAY", "eBay Inc.", "NASDAQ", "Consumer Discretionary"],
  ["ETSY", "Etsy Inc.", "NASDAQ", "Consumer Discretionary"],
  ["CHWY", "Chewy Inc.", "NYSE", "Consumer Discretionary"],
  ["EXPE", "Expedia Group Inc.", "NASDAQ", "Consumer Discretionary"],
  ["DASH", "DoorDash Inc.", "NASDAQ", "Consumer Discretionary"],
  ["F", "Ford Motor Company", "NYSE", "Consumer Discretionary"],
  ["GM", "General Motors Company", "NYSE", "Consumer Discretionary"],
  ["TM", "Toyota Motor Corporation", "NYSE", "Consumer Discretionary"],
  ["HMC", "Honda Motor Co. Ltd.", "NYSE", "Consumer Discretionary"],
  ["RIVN", "Rivian Automotive Inc.", "NASDAQ", "Consumer Discretionary"],
  ["LCID", "Lucid Group Inc.", "NASDAQ", "Consumer Discretionary"],
  ["NIO", "NIO Inc.", "NYSE", "Consumer Discretionary"],
  ["XPEV", "XPeng Inc.", "NYSE", "Consumer Discretionary"],
  ["LI", "Li Auto Inc.", "NASDAQ", "Consumer Discretionary"],
  ["DKNG", "DraftKings Inc.", "NASDAQ", "Consumer Discretionary"],

  /* ---- Energy ---- */
  ["XOM", "Exxon Mobil Corporation", "NYSE", "Energy"],
  ["CVX", "Chevron Corporation", "NYSE", "Energy"],
  ["COP", "ConocoPhillips", "NYSE", "Energy"],
  ["SLB", "Schlumberger Limited", "NYSE", "Energy"],
  ["EOG", "EOG Resources Inc.", "NYSE", "Energy"],
  ["OXY", "Occidental Petroleum Corporation", "NYSE", "Energy"],
  ["MPC", "Marathon Petroleum Corporation", "NYSE", "Energy"],
  ["PSX", "Phillips 66", "NYSE", "Energy"],
  ["VLO", "Valero Energy Corporation", "NYSE", "Energy"],
  ["KMI", "Kinder Morgan Inc.", "NYSE", "Energy"],
  ["WMB", "The Williams Companies Inc.", "NYSE", "Energy"],
  ["OKE", "ONEOK Inc.", "NYSE", "Energy"],
  ["HAL", "Halliburton Company", "NYSE", "Energy"],
  ["BKR", "Baker Hughes Company", "NASDAQ", "Energy"],
  ["DVN", "Devon Energy Corporation", "NYSE", "Energy"],
  ["FANG", "Diamondback Energy Inc.", "NASDAQ", "Energy"],
  ["SHEL", "Shell plc", "NYSE", "Energy"],
  ["BP", "BP p.l.c.", "NYSE", "Energy"],
  ["TTE", "TotalEnergies SE", "NYSE", "Energy"],

  /* ---- Industrials ---- */
  ["BA", "The Boeing Company", "NYSE", "Industrials"],
  ["CAT", "Caterpillar Inc.", "NYSE", "Industrials"],
  ["DE", "Deere & Company", "NYSE", "Industrials"],
  ["GE", "GE Aerospace", "NYSE", "Industrials"],
  ["HON", "Honeywell International Inc.", "NASDAQ", "Industrials"],
  ["RTX", "RTX Corporation", "NYSE", "Industrials"],
  ["LMT", "Lockheed Martin Corporation", "NYSE", "Industrials"],
  ["NOC", "Northrop Grumman Corporation", "NYSE", "Industrials"],
  ["GD", "General Dynamics Corporation", "NYSE", "Industrials"],
  ["UNP", "Union Pacific Corporation", "NYSE", "Industrials"],
  ["UPS", "United Parcel Service Inc.", "NYSE", "Industrials"],
  ["FDX", "FedEx Corporation", "NYSE", "Industrials"],
  ["CSX", "CSX Corporation", "NASDAQ", "Industrials"],
  ["NSC", "Norfolk Southern Corporation", "NYSE", "Industrials"],
  ["WM", "Waste Management Inc.", "NYSE", "Industrials"],
  ["ROK", "Rockwell Automation Inc.", "NYSE", "Industrials"],
  ["EMR", "Emerson Electric Co.", "NYSE", "Industrials"],
  ["ETN", "Eaton Corporation plc", "NYSE", "Industrials"],
  ["ITW", "Illinois Tool Works Inc.", "NYSE", "Industrials"],
  ["PH", "Parker-Hannifin Corporation", "NYSE", "Industrials"],
  ["MMM", "3M Company", "NYSE", "Industrials"],
  ["URI", "United Rentals Inc.", "NYSE", "Industrials"],
  ["PWR", "Quanta Services Inc.", "NYSE", "Industrials"],
  ["GEV", "GE Vernova Inc.", "NYSE", "Industrials"],
  ["AXON", "Axon Enterprise Inc.", "NASDAQ", "Industrials"],
  ["LHX", "L3Harris Technologies Inc.", "NYSE", "Industrials"],
  ["TDG", "TransDigm Group Incorporated", "NYSE", "Industrials"],
  ["DAL", "Delta Air Lines Inc.", "NYSE", "Industrials"],
  ["UAL", "United Airlines Holdings Inc.", "NASDAQ", "Industrials"],
  ["AAL", "American Airlines Group Inc.", "NASDAQ", "Industrials"],
  ["LUV", "Southwest Airlines Co.", "NYSE", "Industrials"],
  ["LYFT", "Lyft Inc.", "NASDAQ", "Industrials"],

  /* ---- Materials ---- */
  ["LIN", "Linde plc", "NASDAQ", "Materials"],
  ["APD", "Air Products and Chemicals Inc.", "NYSE", "Materials"],
  ["SHW", "The Sherwin-Williams Company", "NYSE", "Materials"],
  ["ECL", "Ecolab Inc.", "NYSE", "Materials"],
  ["NEM", "Newmont Corporation", "NYSE", "Materials"],
  ["FCX", "Freeport-McMoRan Inc.", "NYSE", "Materials"],
  ["GOLD", "Barrick Mining Corporation", "NYSE", "Materials"],
  ["NUE", "Nucor Corporation", "NYSE", "Materials"],
  ["STLD", "Steel Dynamics Inc.", "NASDAQ", "Materials"],
  ["DD", "DuPont de Nemours Inc.", "NYSE", "Materials"],
  ["DOW", "Dow Inc.", "NYSE", "Materials"],
  ["PPG", "PPG Industries Inc.", "NYSE", "Materials"],
  ["MLM", "Martin Marietta Materials Inc.", "NYSE", "Materials"],
  ["VMC", "Vulcan Materials Company", "NYSE", "Materials"],
  ["ALB", "Albemarle Corporation", "NYSE", "Materials"],

  /* ---- Utilities ---- */
  ["NEE", "NextEra Energy Inc.", "NYSE", "Utilities"],
  ["SO", "The Southern Company", "NYSE", "Utilities"],
  ["DUK", "Duke Energy Corporation", "NYSE", "Utilities"],
  ["D", "Dominion Energy Inc.", "NYSE", "Utilities"],
  ["AEP", "American Electric Power Company Inc.", "NASDAQ", "Utilities"],
  ["EXC", "Exelon Corporation", "NASDAQ", "Utilities"],
  ["SRE", "Sempra", "NYSE", "Utilities"],
  ["XEL", "Xcel Energy Inc.", "NASDAQ", "Utilities"],
  ["ED", "Consolidated Edison Inc.", "NYSE", "Utilities"],
  ["WEC", "WEC Energy Group Inc.", "NYSE", "Utilities"],
  ["PEG", "Public Service Enterprise Group Inc.", "NYSE", "Utilities"],
  ["VST", "Vistra Corp.", "NYSE", "Utilities"],
  ["CEG", "Constellation Energy Corporation", "NASDAQ", "Utilities"],

  /* ---- Real estate ---- */
  ["PLD", "Prologis Inc.", "NYSE", "Real Estate"],
  ["AMT", "American Tower Corporation", "NYSE", "Real Estate"],
  ["EQIX", "Equinix Inc.", "NASDAQ", "Real Estate"],
  ["SPG", "Simon Property Group Inc.", "NYSE", "Real Estate"],
  ["CCI", "Crown Castle Inc.", "NYSE", "Real Estate"],
  ["PSA", "Public Storage", "NYSE", "Real Estate"],
  ["O", "Realty Income Corporation", "NYSE", "Real Estate"],
  ["WELL", "Welltower Inc.", "NYSE", "Real Estate"],
  ["DLR", "Digital Realty Trust Inc.", "NYSE", "Real Estate"],
  ["AVB", "AvalonBay Communities Inc.", "NYSE", "Real Estate"],
  ["EQR", "Equity Residential", "NYSE", "Real Estate"],

  /* ---- International ADRs & other popular ---- */
  ["BABA", "Alibaba Group Holding Limited", "NYSE", "Consumer Discretionary"],
  ["JD", "JD.com Inc.", "NASDAQ", "Consumer Discretionary"],
  ["PDD", "PDD Holdings Inc.", "NASDAQ", "Consumer Discretionary"],
  ["BIDU", "Baidu Inc.", "NASDAQ", "Communication Services"],
  ["SONY", "Sony Group Corporation", "NYSE", "Technology"],
  ["RY", "Royal Bank of Canada", "NYSE", "Financials"],
  ["TD", "The Toronto-Dominion Bank", "NYSE", "Financials"],
  ["HSBC", "HSBC Holdings plc", "NYSE", "Financials"],
  ["UBS", "UBS Group AG", "NYSE", "Financials"],
  ["SAN", "Banco Santander S.A.", "NYSE", "Financials"],
  ["SAP", "SAP SE", "NYSE", "Technology"],
  ["GME", "GameStop Corp.", "NYSE", "Consumer Discretionary"],
  ["AMC", "AMC Entertainment Holdings Inc.", "NYSE", "Communication Services"],
  ["MARA", "MARA Holdings Inc.", "NASDAQ", "Financials"],
  ["RIOT", "Riot Platforms Inc.", "NASDAQ", "Financials"],
  ["ARKK", "ARK Innovation ETF", "NYSE Arca", "ETF"],

  /* ---- ETFs: benchmarks, bonds, sectors ---- */
  ["SPY", "SPDR S&P 500 ETF Trust", "NYSE Arca", "ETF"],
  ["QQQ", "Invesco QQQ Trust", "NASDAQ", "ETF"],
  ["VOO", "Vanguard S&P 500 ETF", "NYSE Arca", "ETF"],
  ["VTI", "Vanguard Total Stock Market ETF", "NYSE Arca", "ETF"],
  ["IVV", "iShares Core S&P 500 ETF", "NYSE Arca", "ETF"],
  ["DIA", "SPDR Dow Jones Industrial Average ETF", "NYSE Arca", "ETF"],
  ["IWM", "iShares Russell 2000 ETF", "NYSE Arca", "ETF"],
  ["MDY", "SPDR S&P MidCap 400 ETF", "NYSE Arca", "ETF"],
  ["QQQM", "Invesco NASDAQ 100 ETF", "NASDAQ", "ETF"],
  ["SCHG", "Schwab U.S. Large-Cap Growth ETF", "NYSE Arca", "ETF"],
  ["VUG", "Vanguard Growth ETF", "NYSE Arca", "ETF"],
  ["VTV", "Vanguard Value ETF", "NYSE Arca", "ETF"],
  ["AGG", "iShares Core U.S. Aggregate Bond ETF", "NYSE Arca", "ETF"],
  ["BND", "Vanguard Total Bond Market ETF", "NASDAQ", "ETF"],
  ["TLT", "iShares 20+ Year Treasury Bond ETF", "NASDAQ", "ETF"],
  ["IEF", "iShares 7-10 Year Treasury Bond ETF", "NASDAQ", "ETF"],
  ["SHV", "iShares Short Treasury Bond ETF", "NASDAQ", "ETF"],
  ["BIL", "SPDR Bloomberg 1-3 Month T-Bill ETF", "NYSE Arca", "ETF"],
  ["HYG", "iShares iBoxx $ High Yield Corporate Bond ETF", "NYSE Arca", "ETF"],
  ["LQD", "iShares iBoxx $ Investment Grade Corporate Bond ETF", "NYSE Arca", "ETF"],
  ["GLD", "SPDR Gold Shares", "NYSE Arca", "ETF"],
  ["SLV", "iShares Silver Trust", "NYSE Arca", "ETF"],
  ["USO", "United States Oil Fund LP", "NYSE Arca", "ETF"],
  ["VNQ", "Vanguard Real Estate ETF", "NYSE Arca", "ETF"],
  ["SCHD", "Schwab U.S. Dividend Equity ETF", "NYSE Arca", "ETF"],
  ["VYM", "Vanguard High Dividend Yield ETF", "NYSE Arca", "ETF"],
  ["DVY", "iShares Select Dividend ETF", "NASDAQ", "ETF"],
  ["JEPI", "JPMorgan Equity Premium Income ETF", "NYSE Arca", "ETF"],
  ["JEPQ", "JPMorgan Nasdaq Equity Premium Income ETF", "NASDAQ", "ETF"],
  ["XLK", "Technology Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLF", "Financial Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLE", "Energy Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLV", "Health Care Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLI", "Industrial Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLP", "Consumer Staples Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLU", "Utilities Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["XLC", "Communication Services Select Sector SPDR Fund", "NYSE Arca", "ETF"],
  ["SOXX", "iShares Semiconductor ETF", "NASDAQ", "ETF"],
  ["SMH", "VanEck Semiconductor ETF", "NASDAQ", "ETF"],
  ["IBIT", "iShares Bitcoin Trust", "NASDAQ", "ETF"],
  ["FBTC", "Fidelity Wise Origin Bitcoin Fund", "NYSE Arca", "ETF"],
  ["BITO", "ProShares Bitcoin Strategy ETF", "NYSE Arca", "ETF"],
];
